repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        args: ['-l 100']
        language_version: python
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: requirements-txt-fixer
